# Generated by Django 4.2.11 on 2025-08-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(default='RUB', max_length=3),
        ),
    ]
