# Generated by Django 4.2.11 on 2025-08-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date', '-expense_time'], 'verbose_name': 'Трата', 'verbose_name_plural': 'Траты'},
        ),
        migrations.AddField(
            model_name='cashback',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Описание'),
        ),
    ]
