# Generated by Django 4.2.11 on 2025-08-04 09:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_options_cashback_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cashback',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cashback',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.expensecategory'),
        ),
        migrations.AlterUniqueTogether(
            name='cashback',
            unique_together={('profile', 'bank_name', 'month', 'category')},
        ),
        migrations.CreateModel(
            name='RecurringPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('day_of_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='День месяца')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_processed', models.DateField(blank=True, null=True, verbose_name='Последний платеж')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expensecategory')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_payments', to='expenses.profile')),
            ],
            options={
                'verbose_name': 'Регулярный платеж',
                'verbose_name_plural': 'Регулярные платежи',
                'db_table': 'expenses_recurring_payment',
                'indexes': [models.Index(fields=['profile', 'is_active'], name='expenses_re_profile_27b70b_idx'), models.Index(fields=['day_of_month', 'is_active'], name='expenses_re_day_of__a1d9e0_idx')],
            },
        ),
    ]
