# Generated by Django 4.2.11 on 2025-08-04 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_cashback_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('month', 'Месячная подписка'), ('six_months', 'Полугодовая подписка')], max_length=20)),
                ('payment_method', models.CharField(choices=[('stars', 'Telegram Stars')], default='stars', max_length=20)),
                ('amount', models.IntegerField()),
                ('telegram_payment_charge_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='expenses.profile')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'db_table': 'subscriptions',
                'indexes': [models.Index(fields=['profile', 'is_active'], name='subscriptio_profile_6f77a5_idx'), models.Index(fields=['end_date'], name='subscriptio_end_dat_763002_idx')],
            },
        ),
    ]
