# Generated by Django 4.2.11 on 2025-08-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(choices=[('trial', 'Пробный период'), ('stars', 'Telegram Stars')], default='stars', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.CharField(choices=[('trial', 'Пробный период'), ('month', 'Месячная подписка'), ('six_months', 'Полугодовая подписка')], max_length=20),
        ),
    ]
