# Generated by Django 4.2.11 on 2025-08-04 14:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_subscription_notification_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='beta_access_key',
            field=models.CharField(blank=True, help_text='Ключ доступа для бета-тестирования', max_length=50, null=True, verbose_name='Ключ бета-доступа'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_beta_tester',
            field=models.BooleanField(default=False, help_text='Имеет доступ к боту в бета-режиме', verbose_name='Бета-тестер'),
        ),
        migrations.AddField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, help_text='Уникальный реферальный код пользователя', max_length=20, null=True, unique=True, verbose_name='Реферальный код'),
        ),
        migrations.AddField(
            model_name='profile',
            name='referrer',
            field=models.ForeignKey(blank=True, help_text='Кто привел этого пользователя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='expenses.profile', verbose_name='Реферер'),
        ),
        migrations.CreateModel(
            name='ReferralBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_days', models.IntegerField(default=30, verbose_name='Бонусные дни')),
                ('is_activated', models.BooleanField(default=False, verbose_name='Активирован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_bonuses_received', to='expenses.profile', verbose_name='Приглашенный')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_bonuses_given', to='expenses.profile', verbose_name='Реферер')),
                ('subscription', models.ForeignKey(blank=True, help_text='Подписка, за которую начислен бонус', null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.subscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Реферальный бонус',
                'verbose_name_plural': 'Реферальные бонусы',
                'db_table': 'referral_bonuses',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Внутреннее описание промокода', verbose_name='Описание')),
                ('discount_type', models.CharField(choices=[('percent', 'Процент скидки'), ('fixed', 'Фиксированная скидка'), ('days', 'Дополнительные дни')], default='percent', max_length=10, verbose_name='Тип скидки')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Процент (0-100), количество Stars или дни', max_digits=5, verbose_name='Значение скидки')),
                ('max_uses', models.IntegerField(default=0, help_text='0 = без ограничений', verbose_name='Макс. использований')),
                ('used_count', models.IntegerField(default=0, verbose_name='Использований')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Действует с')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promocodes', to='expenses.profile', verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'db_table': 'promocodes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Использован')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocode_usages', to='expenses.profile', verbose_name='Пользователь')),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='expenses.promocode', verbose_name='Промокод')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.subscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Использование промокода',
                'verbose_name_plural': 'Использования промокодов',
                'db_table': 'promocode_usages',
                'unique_together': {('promocode', 'profile')},
            },
        ),
    ]
