# Generated by Django 4.2.11 on 2025-08-04 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_profile_beta_access_key_profile_is_beta_tester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('trial', 'Пробный период'), ('stars', 'Telegram Stars')], default='stars', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.CharField(blank=True, choices=[('trial', 'Пробный период'), ('month', 'Месячная подписка'), ('six_months', 'Полугодовая подписка')], default='month', max_length=20),
        ),
    ]
