# Generated by Django 4.2.11 on 2025-08-04 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_remove_profile_first_name_remove_profile_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='expenses.expensecategory')),
            ],
            options={
                'verbose_name': 'Ключевое слово категории',
                'verbose_name_plural': 'Ключевые слова категорий',
                'db_table': 'expenses_category_keyword',
                'indexes': [models.Index(fields=['category', 'keyword'], name='expenses_ca_categor_ff75cf_idx')],
                'unique_together': {('category', 'keyword')},
            },
        ),
    ]
