# Generated by Django 4.2.11 on 2025-08-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_categorykeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorykeyword',
            name='auto_usage_count',
            field=models.IntegerField(default=0, verbose_name='Автоматические определения'),
        ),
        migrations.AddField(
            model_name='categorykeyword',
            name='last_used',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее использование'),
        ),
        migrations.AddField(
            model_name='categorykeyword',
            name='manual_usage_count',
            field=models.IntegerField(default=0, verbose_name='Ручные исправления'),
        ),
        migrations.AddField(
            model_name='categorykeyword',
            name='normalized_weight',
            field=models.FloatField(default=1.0, verbose_name='Нормализованный вес'),
        ),
        migrations.AddIndex(
            model_name='categorykeyword',
            index=models.Index(fields=['normalized_weight'], name='expenses_ca_normali_a5af6b_idx'),
        ),
    ]
