# Generated by Django 4.2.11 on 2025-08-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_categorykeyword_auto_usage_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorykeyword',
            name='auto_usage_count',
        ),
        migrations.RemoveField(
            model_name='categorykeyword',
            name='last_used',
        ),
        migrations.RemoveField(
            model_name='categorykeyword',
            name='manual_usage_count',
        ),
        migrations.AddField(
            model_name='categorykeyword',
            name='usage_count',
            field=models.IntegerField(default=0, verbose_name='Количество использований'),
        ),
    ]
