# Generated by Django 4.2.11 on 2025-08-07 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_migrate_usage_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='notification_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='weekly_summary_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='daily_reminder_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='daily_reminder_time',
            field=models.TimeField(default=datetime.time(21, 0)),
        ),
    ]
