# Generated by Django 4.2.11 on 2025-08-07 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_usersettings_notification_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='daily_reminder_enabled',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='daily_reminder_time',
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='notification_time',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
    ]
