# Generated by Django 4.2.11 on 2025-08-08 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0014_remove_usersettings_daily_reminder_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('week', 'За неделю'), ('three_days', 'За 3 дня'), ('one_day', 'За день')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='expenses.subscription')),
            ],
            options={
                'verbose_name': 'Уведомление о подписке',
                'verbose_name_plural': 'Уведомления о подписках',
                'db_table': 'subscription_notifications',
                'unique_together': {('subscription', 'notification_type')},
            },
        ),
    ]
