# Generated by Django 4.2.11 on 2025-08-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_subscriptionnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cashback_excluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptionnotification',
            name='notification_type',
            field=models.CharField(choices=[('one_day', 'За день')], max_length=20),
        ),
    ]
