# Generated by Django 4.2.11 on 2025-08-26 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0016_add_cashback_excluded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringpayment',
            options={'verbose_name': 'Ежемесячный платеж', 'verbose_name_plural': 'Ежемесячные платежи'},
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='weekly_summary_day',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='weekly_summary_enabled',
        ),
    ]
