# Generated by Django 4.2.11 on 2025-08-26 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0017_remove_weekly_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='monthly_summary_enabled',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='notification_time',
        ),
    ]
