# Generated by Django 4.2.11 on 2025-09-03 07:57

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0019_add_cashback_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='💵', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_categories', to='expenses.profile')),
            ],
            options={
                'verbose_name': 'Категория доходов',
                'verbose_name_plural': 'Категории доходов',
                'db_table': 'incomes_category',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('income_date', models.DateField(default=datetime.date.today)),
                ('income_time', models.TimeField(default=datetime.datetime.now)),
                ('income_type', models.CharField(choices=[('salary', 'Зарплата'), ('bonus', 'Премия'), ('freelance', 'Фриланс'), ('investment', 'Инвестиции'), ('gift', 'Подарок'), ('refund', 'Возврат'), ('cashback', 'Кешбэк'), ('other', 'Прочее')], default='other', max_length=20)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_day', models.IntegerField(blank=True, help_text='День месяца для регулярных доходов', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('ai_categorized', models.BooleanField(default=False)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='expenses.incomecategory')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='expenses.profile')),
            ],
            options={
                'verbose_name': 'Доход',
                'verbose_name_plural': 'Доходы',
                'db_table': 'incomes_income',
                'ordering': ['-income_date', '-income_time'],
            },
        ),
        migrations.AddIndex(
            model_name='incomecategory',
            index=models.Index(fields=['profile', 'name'], name='incomes_cat_profile_1b25b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='incomecategory',
            unique_together={('profile', 'name')},
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['profile', '-income_date'], name='incomes_inc_profile_fa76e0_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['profile', 'category', '-income_date'], name='incomes_inc_profile_587670_idx'),
        ),
    ]
