# Generated by Django 4.2.11 on 2025-09-03 07:59

from django.db import migrations


def create_default_income_categories(apps, schema_editor):
    """Создать категории доходов по умолчанию для всех существующих профилей"""
    IncomeCategory = apps.get_model('expenses', 'IncomeCategory')
    Profile = apps.get_model('expenses', 'Profile')
    
    # Список категорий доходов по умолчанию с иконками
    default_categories = [
        ('💼 Зарплата', '💼'),
        ('🎁 Премии и бонусы', '🎁'),
        ('💻 Фриланс', '💻'),
        ('📈 Инвестиции', '📈'),
        ('🏦 Проценты по вкладам', '🏦'),
        ('🏠 Аренда недвижимости', '🏠'),
        ('💸 Возвраты и компенсации', '💸'),
        ('💳 Кешбэк', '💳'),
        ('🎉 Подарки', '🎉'),
        ('💰 Прочие доходы', '💰'),
    ]
    
    # Создаем категории для каждого существующего профиля
    for profile in Profile.objects.all():
        # Проверяем, есть ли уже категории доходов у профиля
        if not profile.income_categories.exists():
            income_categories = []
            for name, icon in default_categories:
                # Создаем категорию с эмодзи в названии
                income_categories.append(
                    IncomeCategory(
                        profile=profile,
                        name=name,
                        icon=icon,
                        is_active=True,
                        is_default=False
                    )
                )
            # Массовое создание категорий
            if income_categories:
                IncomeCategory.objects.bulk_create(income_categories, ignore_conflicts=True)


def reverse_default_income_categories(apps, schema_editor):
    """Удалить категории доходов по умолчанию"""
    IncomeCategory = apps.get_model('expenses', 'IncomeCategory')
    # Удаляем только категории с названиями по умолчанию
    default_names = [
        '💼 Зарплата',
        '🎁 Премии и бонусы',
        '💻 Фриланс',
        '📈 Инвестиции',
        '🏦 Проценты по вкладам',
        '🏠 Аренда недвижимости',
        '💸 Возвраты и компенсации',
        '💳 Кешбэк',
        '🎉 Подарки',
        '💰 Прочие доходы',
    ]
    IncomeCategory.objects.filter(name__in=default_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0020_incomecategory_income_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_income_categories, reverse_default_income_categories),
    ]
