# Generated by Django 4.2.11 on 2025-09-03 17:58

from django.db import migrations, models
import django.db.models.deletion


def migrate_category_data(apps, schema_editor):
    """Переносит данные из старого поля category в новое expense_category"""
    RecurringPayment = apps.get_model('expenses', 'RecurringPayment')
    
    for payment in RecurringPayment.objects.all():
        # Сохраняем старую категорию в новое поле expense_category
        if hasattr(payment, 'category') and payment.category:
            payment.expense_category = payment.category
            payment.operation_type = 'expense'
            payment.save()


def reverse_migrate_category_data(apps, schema_editor):
    """Откат миграции данных"""
    RecurringPayment = apps.get_model('expenses', 'RecurringPayment')
    
    for payment in RecurringPayment.objects.all():
        if payment.expense_category:
            payment.category = payment.expense_category
            payment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0021_add_default_income_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringpayment',
            options={'verbose_name': 'Регулярная операция', 'verbose_name_plural': 'Регулярные операции'},
        ),
        
        # Сначала добавляем новые поля
        migrations.AddField(
            model_name='recurringpayment',
            name='expense_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expenses', to='expenses.expensecategory', verbose_name='Категория расхода'),
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='income_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_incomes', to='expenses.incomecategory', verbose_name='Категория дохода'),
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='operation_type',
            field=models.CharField(choices=[('expense', 'Расход'), ('income', 'Доход')], db_index=True, default='expense', max_length=10, verbose_name='Тип операции'),
        ),
        
        # Переносим данные
        migrations.RunPython(migrate_category_data, reverse_migrate_category_data),
        
        # Теперь удаляем старое поле
        migrations.RemoveField(
            model_name='recurringpayment',
            name='category',
        ),
        
        # Добавляем индекс
        migrations.AddIndex(
            model_name='recurringpayment',
            index=models.Index(fields=['operation_type', 'is_active'], name='expenses_re_operati_91b2c2_idx'),
        ),
        
        # НЕ добавляем constraint сразу - сделаем это в отдельной миграции после проверки данных
    ]