# Generated by Django 4.2.11 on 2025-09-03 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0021_add_default_income_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringpayment',
            options={'verbose_name': 'Регулярная операция', 'verbose_name_plural': 'Регулярные операции'},
        ),
        migrations.RemoveField(
            model_name='recurringpayment',
            name='category',
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='expense_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expenses', to='expenses.expensecategory', verbose_name='Категория расхода'),
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='income_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_incomes', to='expenses.incomecategory', verbose_name='Категория дохода'),
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='operation_type',
            field=models.CharField(choices=[('expense', 'Расход'), ('income', 'Доход')], db_index=True, default='expense', max_length=10, verbose_name='Тип операции'),
        ),
        migrations.AddIndex(
            model_name='recurringpayment',
            index=models.Index(fields=['operation_type', 'is_active'], name='expenses_re_operati_91b2c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurringpayment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('expense_category__isnull', False), ('operation_type', 'expense')), models.Q(('income_category__isnull', False), ('operation_type', 'income')), _connector='OR'), name='category_type_consistency'),
        ),
    ]
