# Generated by Django 4.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0023_add_performance_indexes'),
    ]

    operations = [
        # Добавляем constraint после того, как данные корректно перенесены
        migrations.AddConstraint(
            model_name='recurringpayment',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(('expense_category__isnull', False), ('income_category__isnull', True), ('operation_type', 'expense')),
                    models.Q(('income_category__isnull', False), ('expense_category__isnull', True), ('operation_type', 'income')),
                    _connector='OR'
                ),
                name='category_type_consistency'
            ),
        ),
    ]