# Generated by Django 4.2.11 on 2025-09-04 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0024_add_category_type_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeCategoryKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=100)),
                ('usage_count', models.IntegerField(default=0, verbose_name='Количество использований')),
                ('normalized_weight', models.FloatField(default=1.0, verbose_name='Нормализованный вес')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ключевое слово категории дохода',
                'verbose_name_plural': 'Ключевые слова категорий доходов',
                'db_table': 'expenses_income_category_keyword',
            },
        ),
        migrations.RemoveConstraint(
            model_name='recurringpayment',
            name='category_type_consistency',
        ),
        migrations.RemoveIndex(
            model_name='cashback',
            name='idx_cashback_profile_month',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='idx_expense_date',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='idx_expense_profile_date',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='idx_expense_profile_recent',
        ),
        migrations.RemoveIndex(
            model_name='expensecategory',
            name='idx_category_profile_active',
        ),
        migrations.RemoveIndex(
            model_name='income',
            name='idx_income_date',
        ),
        migrations.RemoveIndex(
            model_name='income',
            name='idx_income_profile_date',
        ),
        migrations.RemoveIndex(
            model_name='income',
            name='idx_income_profile_recent',
        ),
        migrations.RemoveIndex(
            model_name='incomecategory',
            name='idx_income_cat_profile_active',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='idx_profile_telegram_id',
        ),
        migrations.RemoveIndex(
            model_name='recurringpayment',
            name='idx_recurring_day_active',
        ),
        migrations.RemoveIndex(
            model_name='recurringpayment',
            name='idx_recurring_profile_active',
        ),
        migrations.RemoveIndex(
            model_name='subscription',
            name='idx_sub_profile_active_end',
        ),
        migrations.AddConstraint(
            model_name='recurringpayment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('expense_category__isnull', False), ('operation_type', 'expense')), models.Q(('income_category__isnull', False), ('operation_type', 'income')), _connector='OR'), name='category_type_consistency'),
        ),
        migrations.AddField(
            model_name='incomecategorykeyword',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='expenses.incomecategory'),
        ),
        migrations.AddIndex(
            model_name='incomecategorykeyword',
            index=models.Index(fields=['keyword'], name='expenses_in_keyword_bfc5a5_idx'),
        ),
        migrations.AddIndex(
            model_name='incomecategorykeyword',
            index=models.Index(fields=['category', 'usage_count'], name='expenses_in_categor_e49401_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='incomecategorykeyword',
            unique_together={('category', 'keyword')},
        ),
    ]
