# Generated by Django 4.2.11 on 2025-09-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0025_add_income_category_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_activity',
            field=models.DateTimeField(blank=True, help_text='Время последней активности пользователя', null=True, verbose_name='Последняя активность'),
        ),
    ]
