# Generated by Django 4.2.11 on 2025-09-05 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0026_add_last_activity_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Реферальный код')),
                ('telegram_link', models.URLField(help_text='Полная реферальная ссылка t.me/bot?start=ref_CODE', verbose_name='Ссылка Telegram')),
                ('clicks', models.IntegerField(default=0, verbose_name='Количество переходов')),
                ('conversions', models.IntegerField(default=0, verbose_name='Количество конверсий')),
                ('total_earned', models.IntegerField(default=0, verbose_name='Всего заработано звёзд')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_link', to='expenses.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Реферальная ссылка',
                'verbose_name_plural': 'Реферальные ссылки',
                'db_table': 'affiliate_links',
            },
        ),
        migrations.CreateModel(
            name='AffiliateProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_permille', models.IntegerField(help_text='100 = 10%, 200 = 20%, максимум определяется Telegram', verbose_name='Комиссия в промилле')),
                ('duration_months', models.IntegerField(blank=True, help_text='Оставьте пустым для бессрочной программы', null=True, verbose_name='Срок действия (месяцы)')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата запуска')),
                ('end_date', models.DateTimeField(blank=True, help_text='Автоматически рассчитывается из duration_months', null=True, verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('telegram_program_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID программы в Telegram')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Реферальная программа',
                'verbose_name_plural': 'Реферальные программы',
                'db_table': 'affiliate_program',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('first_payment_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата первого платежа')),
                ('total_payments', models.IntegerField(default=0, verbose_name='Всего платежей')),
                ('total_spent', models.IntegerField(default=0, verbose_name='Всего потрачено звёзд')),
                ('affiliate_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='expenses.affiliatelink', verbose_name='Реферальная ссылка')),
                ('referred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='expenses.profile', verbose_name='Приглашённый пользователь')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_users', to='expenses.profile', verbose_name='Реферер')),
            ],
            options={
                'verbose_name': 'Реферальная связь',
                'verbose_name_plural': 'Реферальные связи',
                'db_table': 'affiliate_referrals',
                'unique_together': {('referred',)},
            },
        ),
        migrations.CreateModel(
            name='AffiliateCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.IntegerField(verbose_name='Сумма платежа (звёзды)')),
                ('commission_amount', models.IntegerField(verbose_name='Сумма комиссии (звёзды)')),
                ('commission_rate', models.IntegerField(verbose_name='Ставка комиссии (промилле)')),
                ('telegram_transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID транзакции Telegram')),
                ('telegram_payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежа в Telegram')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('hold', 'На холде'), ('paid', 'Выплачено'), ('cancelled', 'Отменено'), ('refunded', 'Возвращено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('hold_until', models.DateTimeField(blank=True, help_text='21 день с момента платежа', null=True, verbose_name='Холд до')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выплаты')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='expenses.affiliatereferral', verbose_name='Реферальная связь')),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_generated', to='expenses.profile', verbose_name='Приглашённый')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_earned', to='expenses.profile', verbose_name='Реферер')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_commissions', to='expenses.subscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Комиссия реферера',
                'verbose_name_plural': 'Комиссии рефереров',
                'db_table': 'affiliate_commissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['referrer', 'status'], name='affiliate_c_referre_b2c9fe_idx'), models.Index(fields=['telegram_transaction_id'], name='affiliate_c_telegra_c960b8_idx'), models.Index(fields=['created_at'], name='affiliate_c_created_d5ab9e_idx')],
            },
        ),
    ]
