# Generated by Django 4.2.11 on 2025-09-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0027_add_affiliate_program_models'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='affiliatecommission',
            index=models.Index(fields=['telegram_payment_id'], name='affiliate_c_telegra_f59679_idx'),
        ),
        migrations.AddConstraint(
            model_name='affiliatecommission',
            constraint=models.UniqueConstraint(condition=models.Q(('telegram_payment_id__isnull', False)), fields=('telegram_payment_id',), name='unique_telegram_payment_id'),
        ),
    ]
