# Generated by Django 4.2.11 on 2025-09-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0028_add_affiliate_payment_constraints'),
    ]

    operations = [
        # Добавляем новые поля в ExpenseCategory
        migrations.AddField(
            model_name='expensecategory',
            name='name_ru',
            field=models.CharField(max_length=100, blank=True, null=True, verbose_name='Название на русском'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='name_en',
            field=models.CharField(max_length=100, blank=True, null=True, verbose_name='Название на английском'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='original_language',
            field=models.CharField(
                max_length=10,
                choices=[('ru', 'Russian'), ('en', 'English'), ('mixed', 'Mixed')],
                default='ru',
                verbose_name='Язык оригинала'
            ),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='is_translatable',
            field=models.BooleanField(default=True, verbose_name='Требует перевода'),
        ),
        
        # Добавляем поле language в CategoryKeyword
        migrations.AddField(
            model_name='categorykeyword',
            name='language',
            field=models.CharField(
                max_length=10,
                choices=[('ru', 'Russian'), ('en', 'English')],
                default='ru',
                verbose_name='Язык ключевого слова'
            ),
        ),
        
        # Добавляем новые индексы
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['profile', 'name_ru'], name='expenses_ca_prof_name_ru_idx'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['profile', 'name_en'], name='expenses_ca_prof_name_en_idx'),
        ),
    ]
