# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0030_migrate_existing_categories_data'),
    ]

    operations = [
        # Добавляем новые поля к IncomeCategory
        migrations.AddField(
            model_name='incomecategory',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название (RU)'),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='original_language',
            field=models.CharField(
                choices=[('ru', 'Русский'), ('en', 'English'), ('other', 'Other')],
                default='ru',
                max_length=10,
                verbose_name='Оригинальный язык'
            ),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='is_translatable',
            field=models.BooleanField(default=True, verbose_name='Переводить автоматически'),
        ),
        
        # Добавляем индексы
        migrations.AddIndex(
            model_name='incomecategory',
            index=models.Index(fields=['profile', 'name_ru'], name='incomes_cat_profile_name_ru_idx'),
        ),
        migrations.AddIndex(
            model_name='incomecategory',
            index=models.Index(fields=['profile', 'name_en'], name='incomes_cat_profile_name_en_idx'),
        ),
    ]