# Generated by Django 4.2.11 on 2025-09-07 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0032_migrate_income_categories_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top5Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('message_id', models.BigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Закреп Топ‑5',
                'verbose_name_plural': 'Закрепы Топ‑5',
                'db_table': 'top5_pins',
            },
        ),
        migrations.CreateModel(
            name='Top5Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateField()),
                ('window_end', models.DateField()),
                ('items', models.JSONField(default=list)),
                ('hash', models.CharField(db_index=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Снепшот Топ‑5',
                'verbose_name_plural': 'Снепшоты Топ‑5',
                'db_table': 'top5_snapshots',
            },
        ),
        migrations.RenameIndex(
            model_name='expensecategory',
            new_name='expenses_ca_profile_dc990d_idx',
            old_name='expenses_ca_prof_name_ru_idx',
        ),
        migrations.RenameIndex(
            model_name='expensecategory',
            new_name='expenses_ca_profile_89e9e8_idx',
            old_name='expenses_ca_prof_name_en_idx',
        ),
        migrations.RenameIndex(
            model_name='incomecategory',
            new_name='incomes_cat_profile_b44274_idx',
            old_name='incomes_cat_profile_name_ru_idx',
        ),
        migrations.RenameIndex(
            model_name='incomecategory',
            new_name='incomes_cat_profile_909cce_idx',
            old_name='incomes_cat_profile_name_en_idx',
        ),
        migrations.AlterUniqueTogether(
            name='categorykeyword',
            unique_together={('category', 'keyword', 'language')},
        ),
        migrations.AddIndex(
            model_name='categorykeyword',
            index=models.Index(fields=['language'], name='expenses_ca_languag_298319_idx'),
        ),
        migrations.AddField(
            model_name='top5snapshot',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='top5_snapshot', to='expenses.profile'),
        ),
        migrations.AddField(
            model_name='top5pin',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='top5_pin', to='expenses.profile'),
        ),
    ]
