# Generated by Django 4.2.11 on 2025-09-08 13:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0034_systemhealthcheck_aiservicemetrics_useranalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cashback_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
