# Generated by Django 4.2.11 on 2025-09-08 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0036_add_households'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyinvite',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата использования'),
        ),
        migrations.AddField(
            model_name='familyinvite',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invites', to='expenses.profile', verbose_name='Использовано пользователем'),
        ),
        migrations.AddField(
            model_name='household',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_households', to='expenses.profile', verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='household',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='household',
            name='max_members',
            field=models.IntegerField(default=10, verbose_name='Максимум участников'),
        ),
        migrations.AddIndex(
            model_name='familyinvite',
            index=models.Index(fields=['token'], name='family_invi_token_115d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='familyinvite',
            index=models.Index(fields=['is_active', 'expires_at'], name='family_invi_is_acti_27c2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='household',
            index=models.Index(fields=['is_active'], name='households_is_acti_42e5dc_idx'),
        ),
    ]
