# Generated by Django 5.0.9 on 2025-09-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0040_add_legal_acceptance_flags'),
    ]

    operations = [
        # Удаляем поля старой реферальной системы из модели Profile
        migrations.RemoveField(
            model_name='profile',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='referral_code',
        ),
        # Удаляем модель ReferralBonus (старая система с бонусными днями)
        migrations.DeleteModel(
            name='ReferralBonus',
        ),
    ]