# Generated by Django 5.0.9 on 2025-09-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0041_remove_old_referral_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='applicable_subscription_types',
            field=models.CharField(choices=[('all', 'Все подписки'), ('month', 'Только месячная'), ('six_months', 'Только на 6 месяцев')], default='all', help_text='К каким типам подписок применим промокод', max_length=20, verbose_name='Применимо к'),
        ),
    ]
