# Generated by Django 4.2.11 on 2025-09-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0043_affiliaterewardfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_payments_count',
            field=models.IntegerField(default=0, help_text='Общее количество платежей через Telegram Stars', verbose_name='Всего платежей'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_stars_paid',
            field=models.IntegerField(default=0, help_text='Общее количество уплаченных Telegram Stars', verbose_name='Всего уплачено звезд'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('trial', 'Пробный период'), ('stars', 'Telegram Stars'), ('referral', 'Реферальное продление')], default='stars', max_length=20),
        ),
    ]
