# Generated by Django 5.0.9 on 2025-09-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0044_profile_total_payments_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='acquisition_campaign',
            field=models.CharField(blank=True, db_index=True, help_text='Название кампании или канала (имя блогера, название рекламы и т.д.)', max_length=100, null=True, verbose_name='Кампания/Канал'),
        ),
        migrations.AddField(
            model_name='profile',
            name='acquisition_date',
            field=models.DateTimeField(blank=True, help_text='Дата первого перехода по ссылке', null=True, verbose_name='Дата привлечения'),
        ),
        migrations.AddField(
            model_name='profile',
            name='acquisition_details',
            field=models.JSONField(blank=True, default=dict, help_text='Дополнительные данные об источнике (utm_content, utm_term и т.д.)', null=True, verbose_name='Дополнительные данные'),
        ),
        migrations.AddField(
            model_name='profile',
            name='acquisition_source',
            field=models.CharField(blank=True, choices=[('organic', 'Органический'), ('blogger', 'Блогер'), ('ads', 'Реклама'), ('referral', 'Реферал'), ('social', 'Соцсети'), ('other', 'Другое')], db_index=True, help_text='Источник привлечения: blogger, ads, organic, referral', max_length=50, null=True, verbose_name='Источник привлечения'),
        ),
    ]
