# Generated by Django 5.0.9 on 2025-09-22 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0045_add_utm_tracking_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiserCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: ivan, maria, yandex', max_length=100, verbose_name='Имя рекламодателя')),
                ('campaign', models.CharField(blank=True, help_text='Например: stories, december2024, black_friday', max_length=100, verbose_name='Название кампании')),
                ('utm_code', models.CharField(db_index=True, help_text='Автоматически генерируется, например: b_ivan_stories', max_length=200, unique=True, verbose_name='UTM-код')),
                ('source_type', models.CharField(choices=[('blogger', 'Блогер/Инфлюенсер'), ('ads', 'Платная реклама'), ('social', 'Социальные сети'), ('referral', 'Реферальная программа'), ('organic', 'Органический трафик'), ('other', 'Другое')], default='blogger', max_length=20, verbose_name='Тип источника')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивные кампании не отображаются в статистике', verbose_name='Активна')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активная'), ('paused', 'Приостановлена'), ('completed', 'Завершена')], default='active', max_length=20, verbose_name='Статус кампании')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Планируемый бюджет кампании', max_digits=12, null=True, verbose_name='Бюджет (₽)')),
                ('target_users', models.IntegerField(blank=True, help_text='Планируемое количество привлеченных пользователей', null=True, verbose_name='Целевое количество пользователей')),
                ('target_conversion', models.DecimalField(blank=True, decimal_places=2, help_text='Планируемая конверсия в платящих', max_digits=5, null=True, verbose_name='Целевая конверсия (%)')),
                ('description', models.TextField(blank=True, help_text='Детали кампании, условия сотрудничества и т.д.', verbose_name='Описание')),
                ('contact_info', models.CharField(blank=True, help_text='Телефон, email или Telegram рекламодателя', max_length=255, verbose_name='Контактная информация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Рекламная кампания',
                'verbose_name_plural': 'Рекламные кампании',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['utm_code'], name='expenses_ad_utm_cod_bb423f_idx'), models.Index(fields=['source_type', 'is_active'], name='expenses_ad_source__ce1752_idx'), models.Index(fields=['created_at'], name='expenses_ad_created_1c7c38_idx')],
            },
        ),
    ]
