# Generated by Django 5.0.9 on 2025-09-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0046_advertisercampaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisercampaign',
            name='contact_info',
            field=models.CharField(blank=True, help_text='Телефон, email или Telegram рекламопроизводителя', max_length=255, verbose_name='Контактная информация'),
        ),
        migrations.AlterField(
            model_name='advertisercampaign',
            name='name',
            field=models.CharField(help_text='Например: ivan, maria, yandex', max_length=100, verbose_name='Имя рекламопроизводителя'),
        ),
    ]
