# Generated by Django 4.2.11 on 2025-10-09 14:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0047_rename_advertiser_to_producer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, verbose_name='Год')),
                ('month', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Месяц')),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Всего расходов')),
                ('total_incomes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Всего доходов')),
                ('expenses_count', models.IntegerField(default=0, verbose_name='Количество трат')),
                ('top_categories', models.JSONField(default=list, help_text='[{"category": "name", "amount": 1000, "percentage": 25}]', verbose_name='Топ категорий')),
                ('ai_summary', models.TextField(help_text='Краткое резюме трат за месяц от AI', verbose_name='AI резюме месяца')),
                ('ai_analysis', models.TextField(help_text='Детальный анализ трат и паттернов', verbose_name='AI анализ')),
                ('ai_recommendations', models.TextField(help_text='Рекомендации по оптимизации бюджета', verbose_name='AI рекомендации')),
                ('ai_model_used', models.CharField(max_length=100, verbose_name='Использованная AI модель')),
                ('ai_provider', models.CharField(choices=[('openai', 'OpenAI'), ('google', 'Google AI')], max_length=50, verbose_name='AI провайдер')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата генерации')),
                ('regeneration_count', models.IntegerField(default=0, verbose_name='Количество регенераций')),
                ('last_regenerated_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя регенерация')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='Просмотрено')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата просмотра')),
                ('user_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка пользователя')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_insights', to='expenses.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Месячный инсайт',
                'verbose_name_plural': 'Месячные инсайты',
                'db_table': 'monthly_insights',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['profile', '-year', '-month'], name='monthly_ins_profile_123b1e_idx'), models.Index(fields=['generated_at'], name='monthly_ins_generat_9072d3_idx')],
                'unique_together': {('profile', 'year', 'month')},
            },
        ),
    ]
