# Generated by Django 4.2.20 on 2025-11-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0048_monthlyinsight'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorykeyword',
            name='last_used',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее использование'),
        ),
        migrations.AddField(
            model_name='incomecategorykeyword',
            name='last_used',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее использование'),
        ),
        migrations.AlterField(
            model_name='categorykeyword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='incomecategorykeyword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AddIndex(
            model_name='categorykeyword',
            index=models.Index(fields=['last_used'], name='expenses_ca_last_us_ee2c94_idx'),
        ),
        migrations.AddIndex(
            model_name='incomecategorykeyword',
            index=models.Index(fields=['last_used'], name='expenses_in_last_us_707772_idx'),
        ),
    ]
