# Generated by Django 4.2.20 on 2025-11-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0048_monthlyinsight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorykeyword',
            name='usage_count',
            field=models.FloatField(default=0.0, verbose_name='Количество использований'),
        ),
        migrations.AlterField(
            model_name='incomecategorykeyword',
            name='usage_count',
            field=models.FloatField(default=0.0, verbose_name='Количество использований'),
        ),
    ]
