# Generated by Django 4.2.20 on 2025-11-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0049_categorykeyword_last_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bot_blocked',
            field=models.BooleanField(db_index=True, default=False, help_text='Пользователь заблокировал бота', verbose_name='Бот заблокирован'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bot_blocked_at',
            field=models.DateTimeField(blank=True, help_text='Когда пользователь заблокировал бота', null=True, verbose_name='Дата блокировки'),
        ),
    ]
