# Generated by Django 4.2.20 on 2025-11-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0050_add_bot_blocked_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='categorykeyword',
            name='expenses_ca_normali_a5af6b_idx',
        ),
        migrations.RemoveField(
            model_name='categorykeyword',
            name='normalized_weight',
        ),
        migrations.RemoveField(
            model_name='incomecategorykeyword',
            name='normalized_weight',
        ),
    ]
