# Generated by Django 4.2.20 on 2025-11-18 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0051_remove_normalized_weight_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'Настройки пользователя', 'verbose_name_plural': 'Настройки пользователей'},
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='budget_alerts_enabled',
        ),
    ]
