# Generated by Django 5.0.9 on 2025-11-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0052_remove_budget_alerts_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemhealthcheck',
            name='deepseek_api_response_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='systemhealthcheck',
            name='deepseek_api_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemhealthcheck',
            name='qwen_api_response_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='systemhealthcheck',
            name='qwen_api_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aiservicemetrics',
            name='service',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('google', 'Google Gemini'), ('deepseek', 'DeepSeek'), ('qwen', 'Qwen')], max_length=50),
        ),
    ]
