# Generated by Django 5.0.9 on 2025-11-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0053_systemhealthcheck_deepseek_api_response_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyinsight',
            name='ai_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('google', 'Google AI'), ('deepseek', 'DeepSeek'), ('qwen', 'Qwen')], max_length=50, verbose_name='AI �\u0ba2�����'),
        ),
    ]
