# Generated by Django 5.0.9 on 2025-12-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0054_alter_monthlyinsight_ai_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyinsight',
            name='ai_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('google', 'Google AI'), ('deepseek', 'DeepSeek'), ('qwen', 'Qwen'), ('openrouter', 'OpenRouter'), ('basic', 'Basic Summary')], max_length=50, verbose_name='AI �\u0ba2�����'),
        ),
    ]
