# Generated by Django 5.0.9 on 2025-12-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0055_add_openrouter_basic_to_ai_provider_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='income_type',
        ),
    ]
