# Generated by Django 5.1.14 on 2026-02-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0056_remove_income_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='exchange_rate_used',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Использованный курс'),
        ),
        migrations.AddField(
            model_name='expense',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Оригинальная сумма'),
        ),
        migrations.AddField(
            model_name='expense',
            name='original_currency',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Оригинальная валюта'),
        ),
        migrations.AddField(
            model_name='income',
            name='exchange_rate_used',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Использованный курс'),
        ),
        migrations.AddField(
            model_name='income',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Оригинальная сумма'),
        ),
        migrations.AddField(
            model_name='income',
            name='original_currency',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Оригинальная валюта'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='auto_convert_currency',
            field=models.BooleanField(default=False, verbose_name='Автоконвертация валют'),
        ),
    ]
