# Generated by Django 5.1.14 on 2026-02-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0058_enable_auto_convert_for_existing_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='auto_convert_currency',
            field=models.BooleanField(default=True, verbose_name='Автоконвертация валют'),
        ),
    ]
