# Generated by Codex on 2026-03-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0060_alter_useranalytics_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(
                blank=True,
                choices=[
                    ('trial', 'Пробный период'),
                    ('stars', 'Telegram Stars'),
                    ('promo', 'Промокод'),
                    ('referral', 'Реферальное продление'),
                ],
                default='stars',
                max_length=20,
            ),
        ),
    ]
