# Generated by Django 5.1.14 on 2026-04-01 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0061_alter_subscription_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyinsight',
            name='ai_recommendations',
        ),
    ]
