# Generated by Django 5.1.14 on 2026-06-13 03:02

from django.db import migrations, models


def normalize_legacy_budgets(apps, schema_editor):
    """Нормализует существующие строки expenses_budget перед добавлением
    частичных unique-constraint.

    Таблица исторически не использовалась (ожидается 0 строк), но миграция
    обязана быть безопасной для любого состояния прода:
      1. Заполняет currency из валюты профиля (поле только что добавлено с
         default='RUB', здесь выставляем реальную валюту владельца).
      2. Деактивирует дубликаты активных лимитов, оставляя самый свежий
         по (profile, category) и (profile, category IS NULL), иначе
         AddConstraint упадёт с IntegrityError.

    Идемпотентна: повторный прогон ничего не ломает.
    """
    Budget = apps.get_model("expenses", "Budget")

    # 1. Заполнить currency из профиля
    for budget in Budget.objects.select_related("profile").all():
        profile_currency = getattr(budget.profile, "currency", None) or "RUB"
        if budget.currency != profile_currency:
            budget.currency = profile_currency
            budget.save(update_fields=["currency"])

    # 2. Деактивировать дубликаты активных лимитов.
    # Группируем по (profile_id, category_id); category_id=None — общий лимит.
    seen: set = set()
    active_qs = Budget.objects.filter(is_active=True).order_by(
        "profile_id", "category_id", "-updated_at", "-id"
    )
    for budget in active_qs:
        key = (budget.profile_id, budget.category_id)
        if key in seen:
            budget.is_active = False
            budget.save(update_fields=["is_active"])
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0062_remove_monthlyinsight_ai_recommendations"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="currency",
            field=models.CharField(default="RUB", max_length=3),
        ),
        # Нормализация legacy-данных ДО создания constraint (Codex review #6).
        migrations.RunPython(
            normalize_legacy_budgets,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(fields=["profile", "is_active"], name="expenses_bu_profile_861032_idx"),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("category__isnull", False)),
                fields=("profile", "category"),
                name="unique_active_budget_per_category",
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("category__isnull", True)),
                fields=("profile",),
                name="unique_active_total_budget_per_profile",
            ),
        ),
    ]
