# Generated by Django 5.1.14 on 2026-06-14 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0063_budget_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                (
                    'period_type',
                    models.CharField(
                        choices=[
                            ('monthly', 'Месячная'),
                            ('weekly', 'Недельная'),
                            ('daily', 'Дневная'),
                        ],
                        default='monthly',
                        max_length=20,
                    ),
                ),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'category',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='income_budgets',
                        to='expenses.incomecategory',
                    ),
                ),
                (
                    'profile',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='income_budgets',
                        to='expenses.profile',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Цель по доходу',
                'verbose_name_plural': 'Цели по доходам',
                'db_table': 'incomes_income_budget',
                'indexes': [models.Index(fields=['profile', 'is_active'], name='incomes_inc_profile_6d8001_idx')],
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ('is_active', True),
                            ('category__isnull', False),
                        ),
                        fields=('profile', 'category'),
                        name='unique_active_income_goal_per_category',
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ('is_active', True),
                            ('category__isnull', True),
                        ),
                        fields=('profile',),
                        name='unique_active_total_income_goal_per_profile',
                    ),
                ],
            },
        ),
    ]
