# Generated by Django 5.1.14 on 2026-08-16 19:46

from django.db import migrations, models

# Префиксы, которыми bot/services/recurring.py помечает автоматически созданные
# операции ('[Регулярный] ' — легаси-вариант). Используются только для backfill.
RECURRING_PREFIXES = ("[Ежемесячный] ", "[Регулярный] ")


def backfill_is_recurring(apps, schema_editor):
    """Проставить is_recurring существующим операциям, созданным из регулярных платежей.

    До этой миграции единственным признаком был текстовый префикс описания.
    У Income поле is_recurring существовало ранее, но не заполнялось процессором.
    """
    Expense = apps.get_model("expenses", "Expense")
    Income = apps.get_model("expenses", "Income")

    for model in (Expense, Income):
        for prefix in RECURRING_PREFIXES:
            model.objects.filter(
                description__startswith=prefix,
                is_recurring=False,
            ).update(is_recurring=True)


def noop_reverse(apps, schema_editor):
    # Обратная миграция удаляет поле у Expense; данные Income безопасно оставить
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0064_income_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_is_recurring, noop_reverse),
    ]
