# Generated by Django 5.1.14 on 2026-08-16 19:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0065_expense_is_recurring"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyReportLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.IntegerField()),
                (
                    "month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_report_logs",
                        to="expenses.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отправленный месячный отчет",
                "verbose_name_plural": "Отправленные месячные отчеты",
                "db_table": "expenses_monthly_report_log",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "year", "month"), name="uniq_monthly_report_per_profile_period"
                    )
                ],
            },
        ),
    ]
