# Generated by Django 4.2.11 on 2025-09-05 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0025_add_income_category_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Для внутреннего использования', max_length=200, verbose_name='Название рассылки')),
                ('message_text', models.TextField(help_text='Поддерживается Markdown форматирование', verbose_name='Текст сообщения')),
                ('recipient_type', models.CharField(choices=[('all', 'Все пользователи'), ('active', 'Активные пользователи'), ('subscribed', 'Подписчики'), ('trial', 'На пробном периоде'), ('inactive', 'Неактивные'), ('beta', 'Бета-тестеры'), ('custom', 'Выборочно')], default='all', max_length=20, verbose_name='Тип получателей')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланирована'), ('sending', 'Отправляется'), ('completed', 'Завершена'), ('cancelled', 'Отменена'), ('failed', 'Ошибка')], default='draft', max_length=20, verbose_name='Статус')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Оставьте пустым для немедленной отправки', null=True, verbose_name='Дата и время отправки')),
                ('total_recipients', models.IntegerField(default=0, verbose_name='Всего получателей')),
                ('sent_count', models.IntegerField(default=0, verbose_name='Отправлено')),
                ('failed_count', models.IntegerField(default=0, verbose_name='Ошибок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало отправки')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('include_inactive_days', models.IntegerField(blank=True, help_text='Для типа "Неактивные"', null=True, verbose_name='Неактивные более N дней')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('custom_recipients', models.ManyToManyField(blank=True, help_text='Используется только при типе "Выборочно"', to='expenses.profile', verbose_name='Выбранные получатели')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='admin_panel.broadcastmessage')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.profile')),
            ],
            options={
                'verbose_name': 'Получатель рассылки',
                'verbose_name_plural': 'Получатели рассылки',
                'unique_together': {('broadcast', 'profile')},
            },
        ),
    ]
