# Generated by Django 4.2.11 on 2025-10-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0047_rename_advertiser_to_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemhealthcheck',
            name='webhook_pending_updates',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='systemhealthcheck',
            name='webhook_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
